import type { TuningGuideStep } from '../tuningGuideSteps';
import { FLYWHEEL_TUNING_REFERENCE } from '../../reference/flywheelReference';

export const FLYWHEEL_TUNING_GUIDE_STEPS: TuningGuideStep[] = [
  {
    id: 'prepare',
    title: 'Start the simulation',
    body: 'Enable Teleoperated in the Sim Controls bar, then click Run Simulation. Watch the flywheel spin in the Mechanism view and the velocity trace in RPM.',
    prompt: 'Why watch velocity, not position, for a flywheel?',
    checklist: ['Teleoperated enabled', 'Code has no errors', 'Simulation running'],
    advancePrerequisites: ['teleop', 'simRunning', 'validCode'],
  },
  {
    id: 'graph-velocity',
    title: 'Read the velocity graph',
    body: 'TraceView shows wheel RPM. Code and SpringTune use motor rot/s. Convert: wheel RPM = (motor rot/s ÷ gear ratio) × 60.',
    prompt: 'If kSetpoint is 1 motor rot/s and gear ratio is 5, what RPM should the graph show at steady state?',
    highlight: { graph: true },
    needsSim: true,
    advancePrerequisites: ['simRunning'],
  },
  {
    id: 'tune-ks',
    title: 'Tune kS',
    body: 'Start with a small kS (e.g. 0.1). kS helps static friction on real hardware. Simulation friction is minimal — focus on the workflow.',
    prompt: 'What is the smallest kS that still starts motion when setpoint is nonzero?',
    referenceHint: FLYWHEEL_TUNING_REFERENCE.kS.hint,
    highlight: { field: 'kS', graph: true },
    needsSim: true,
    advancePrerequisites: ['simRunning'],
  },
  {
    id: 'tune-kv',
    title: 'Tune kV at 1 rot/s',
    body: 'Set kSetpoint to 1 motor rot/s. Temporarily use kS to find the voltage that holds 1 rot/s: start small, double until velocity hovers near 12 RPM (with 5:1 gear), then fine-tune. Copy that value into kV and reset kS if needed.',
    prompt: 'What kV value holds 1 motor rot/s on your graph?',
    referenceHint: FLYWHEEL_TUNING_REFERENCE.kV.hint,
    checklist: ['Setpoint is 1 motor rot/s', 'Velocity trace near 12 RPM (5:1 gear)', 'kV updated in code'],
    highlight: { field: 'kV', graph: true },
    needsSim: true,
    advancePrerequisites: ['simRunning', 'liveTuning'],
  },
  {
    id: 'target-rpm',
    title: 'Set target velocity',
    body: 'Pick a realistic wheel RPM (lesson example: 417 RPM). Convert to motor rot/s: (RPM ÷ 60) × gear ratio. Update kSetpoint. Verify the trace reaches and holds the target.',
    prompt: 'What motor rot/s matches your target wheel RPM?',
    referenceHint: FLYWHEEL_TUNING_REFERENCE.setpoint.hint,
    highlight: { field: 'setpoint', mechanism: true, graph: true },
    needsSim: true,
    advancePrerequisites: ['simRunning'],
  },
  {
    id: 'tune-kp',
    title: 'Tune kP',
    body: 'kP is very small (try 0.001). Increase if rise time is slow or recovery from disturbances is weak. Too much kP causes oscillation. kV should still do most of the work.',
    prompt: 'Does a small kP improve how quickly the flywheel reaches setpoint?',
    referenceHint: FLYWHEEL_TUNING_REFERENCE.kP.hint,
    highlight: { field: 'kP', graph: true },
    needsSim: true,
    advancePrerequisites: ['simRunning', 'liveTuning'],
  },
  {
    id: 'complete',
    title: 'Next steps',
    body: 'You tuned velocity feedforward and proportional control in the browser. Verify on real hardware with Phoenix Tuner or REV Hardware Client — units and friction will differ.',
    prompt: 'What would you check first on a physical flywheel?',
    advancePrerequisites: ['simRunning'],
  },
];
